version: '3.9'

services:
  backend:
    build: .
    ports:
      - "5500:5500"
    env_file:
      - .env
  #   depends_on:
  #     - redis

  # redis:
  #   image: redis:7
  #   ports:
  #     - "6379:6379"
